spring.application.name=cleanup_system
spring.datasource.url=jdbc:mysql://localhost:${DB_PORT:3308}/${DB_NAME:cleanup_system}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:MySqL11}
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true